#!/usr/bin/env bash
# Re-extract stock templates/prompt.md into do-harness/prompts/l0-general.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HARNESS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$HARNESS_DIR/.." && pwd)"
SRC="$REPO_ROOT/crates/codegen/xai-grok-agent/templates/prompt.md"
DST="$HARNESS_DIR/prompts/l0-general.md"

if [[ ! -f "$SRC" ]]; then
  echo "missing stock template: $SRC" >&2
  exit 1
fi

DATE="$(date -u +%Y-%m-%d 2>/dev/null || date +%Y-%m-%d)"

{
  cat <<HEADER
<!--
  L0 GENERAL — stock grok-build system core (product-owned copy)

  Source: crates/codegen/xai-grok-agent/templates/prompt.md
  Extracted: ${DATE}
  Layer: L0 session-stable (not swapped by Tab role cycle)
  Product path: do-harness/prompts/l0-general.md

  Regenerated by: bash do-harness/scripts/sync-l0-general.sh
  After sync: re-apply product tweaks (e.g. user_guide path) if needed.
  Template syntax: MiniJinja \${{ }} for tools; pi-ness \${name} catalog in placeholders.md
-->

HEADER
  cat "$SRC"
} >"$DST"

echo "wrote $DST from $SRC"
wc -l -c "$DST" "$SRC"
