#!/usr/bin/env bash
# Report feature-flag identifiers declared once but never read elsewhere.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

REPORT_DIR="${REPORT_DIR:-.quality}"
mkdir -p "$REPORT_DIR"
REPORT="$REPORT_DIR/dead-feature-flags.txt"
: >"$REPORT"

# Collect flag-like string literals near feature_flag usage sites.
mapfile -t FLAGS < <(
  git grep -nI -E 'feature[_-]?flag|FeatureFlag|feature_flags' -- \
    'crates/**/*.rs' 'do-harness/**' \
    | grep -oE '"[a-z0-9_]{4,64}"' \
    | tr -d '"' \
    | sort -u \
    || true
)

DEAD=()
for flag in "${FLAGS[@]:-}"; do
  count=$(git grep -I -F "$flag" -- 'crates/**/*.rs' 'do-harness/**' 2>/dev/null | wc -l | tr -d ' ')
  if (( count <= 1 )); then
    DEAD+=("$flag")
    echo "$flag (references=$count)" >>"$REPORT"
  fi
done

{
  echo "# Dead / single-reference feature flag candidates"
  echo "# Generated by scripts/check-dead-feature-flags.sh"
  echo "# Date: $(date -u +%Y-%m-%dT%H:%MZ)"
  echo
  if ((${#DEAD[@]} == 0)); then
    echo "No single-reference flag candidates found."
  else
    printf '%s\n' "${DEAD[@]}"
  fi
} | tee "$REPORT"

# Non-zero only when CI requests hard-fail mode.
if [[ "${DEAD_FLAGS_FAIL:-0}" == "1" && ${#DEAD[@]} -gt 0 ]]; then
  echo "Dead flag candidates present (${#DEAD[@]}). See $REPORT"
  exit 1
fi

echo "Dead feature flag scan complete → $REPORT"
