#!/usr/bin/env bash
# Generate machine-maintained documentation artifacts.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT_DIR=docs/generated
mkdir -p "$OUT_DIR"

# Workspace crate inventory from Cargo.toml members.
{
  echo "# Generated crate inventory"
  echo
  echo "Auto-generated by \`scripts/generate-docs.sh\`. Do not edit by hand."
  echo
  echo "Generated: $(date -u +%Y-%m-%dT%H:%MZ)"
  echo
  echo "| Crate path |"
  echo "|------------|"
  awk '/members = \[/,/\]/' Cargo.toml \
    | grep -E '^\s*"' \
    | sed 's/[",]//g; s/^[[:space:]]*/| /; s/$/ |/'
} >"$OUT_DIR/crate-inventory.md"

# Capability smoke commands extracted from README.
{
  echo "# Generated smoke commands"
  echo
  echo "Extracted from README.md by \`scripts/generate-docs.sh\`."
  echo
  echo '```sh'
  grep -E '^\s*(cargo |# )' README.md | head -40
  echo '```'
} >"$OUT_DIR/smoke-commands.md"

echo "Generated docs under $OUT_DIR"
